// Auto-generated games configuration
// Generated by scripts/build-games-config.js
// Do not edit manually

import { GAME_2048_METADATA } from '../games/2048/config';
import { LIGHTS_OUT_METADATA } from '../games/lights-out/config';
import { MOTS_MELES_METADATA } from '../games/mots-meles/config';
import { SUDOKU_METADATA } from '../games/sudoku/config';
import { TUSMO_METADATA } from '../games/tusmo/config';

import { GameComponent, GameMetadata } from './games';

export const GAMES_CONFIG: Record<
  string,
  {
    component: () => Promise<{ default: GameComponent }>;
    metadata: GameMetadata;
  }
> = {
  '2048': {
    component: () => import('../games/2048'),
    metadata: GAME_2048_METADATA,
  },
  'lights-out': {
    component: () => import('../games/lights-out'),
    metadata: LIGHTS_OUT_METADATA,
  },
  'mots-meles': {
    component: () => import('../games/mots-meles'),
    metadata: MOTS_MELES_METADATA,
  },
  sudoku: {
    component: () => import('../games/sudoku'),
    metadata: SUDOKU_METADATA,
  },
  tusmo: {
    component: () => import('../games/tusmo'),
    metadata: TUSMO_METADATA,
  },
};

export const DISCOVERED_GAMES = [
  '2048',
  'lights-out',
  'mots-meles',
  'sudoku',
  'tusmo',
] as const;

export type DiscoveredGameId = (typeof DISCOVERED_GAMES)[number];
